services:
    remote_code_coverage.remote_code_coverage_listener:
        class: BehatRemoteCodeCoverage\RemoteCodeCoverageListener
        arguments:
            - '@mink'
            - '%mink.base_url%'
            - '%remote_code_coverage.target_directory%'
            - '%remote_code_coverage.split_by%'
        tags:
            - { name: event_dispatcher.subscriber }
